### ISSUE TITLE
Setup Frontend Project with Next.js & TypeScript

### ISSUE THREAD

**Issue by mikehammond** [mowblox/decentralized-vendor-payment-system#1]
Follow the automatic installation guide [here](https://nextjs.org/docs/getting-started/installation).
We are going to be using **Tailwind CSS** so take **YES** for that option as well.
- [x] Ensure project ends up in a folder named `frontend` at the root of the project.
- [x] Project name should be `frontend`.
- [x] Select **YES** for all the questions asked.
- [x] Commit and push your code(s) whiles you are at it.
- [x] Raise a PR to be merged once ready.

**Comment by bc-davin** [comment]
Hey, would like me to take on this issue?

**Comment by mikehammond** [comment]
@bc-davin Please take it away

**Comment by shivam-shukla-71** [comment]
PR-
https://github.com/mowblox/decentralized-vendor-payment-system/pull/4
