### ISSUE TITLE
Legacy npm dependency causing vercel deployment failure

### ISSUE THREAD

**Issue by mikehammond** [mowblox/decentralized-vendor-payment-system#12]
![image](https://github.com/user-attachments/assets/94b71c56-9122-4b0e-b437-4953f63db025)

**Comment by mikehammond** [comment]
@Baah-Danso-Kenneth This BUG was created from the package that you used for icons.

I will recommend we use hero icons from the Tailwind team - https://heroicons.com/
Follow their React guide here - https://github.com/tailwindlabs/heroicons?tab=readme-ov-file#react to get it to replace that legacy icons package.

**Comment by Baah-Danso-Kenneth** [comment]
I have made a PR on the feat/landing-page-ui branch which address the bug
