### ISSUE TITLE
Initialize Blockchain Project using Hardhat

### ISSUE THREAD

**Issue by mikehammond** [mowblox/decentralized-vendor-payment-system#2]
- [ ] Create a folder named **blockchain** in the root of the project.
- [ ] `cd` into the **blockchain** folder.
- [ ] Follow the guide [here](https://hardhat.org/hardhat-runner/docs/guides/project-setup) to initialize the project. Please select the 2nd option (`Create a TypeScript project`).
- [ ] Please do not remove the boilerplate code in the project. Mainly `contracts/Lock.sol`, `tests/Lock.ts` & `ignition/modules/Lock.ts`. We will be using it as reference as we go.
- [ ] Commit and push your code(s) whiles you are at it.
- [ ] Raise a PR to be merged once ready.

**Comment by Sarahlyy** [comment]
@mikehammond I will like to work on this issue

**Comment by mikehammond** [comment]
@Sarahlyy Please take it away

**Comment by mikehammond** [comment]
@Sarahlyy How is the reworking on this issue going?

**Comment by BraKoose** [comment]
@mikehammond is issue still open for other to contribute?

**Comment by mikehammond** [comment]
@BraKoose This issue is still open but I want to get some feedback from @Sarahlyy first since she made a first attempt to work on it.

**Comment by Sarahlyy** [comment]
@mikehammond I just submitted a pull request. I used the video on the telegram page as a guide. Hope I am on the right track.

**Comment by mikehammond** [comment]
@Sarahlyy Excellent, I can see your PR now.
Let me review it and see if it can be merged.

**Comment by ProfOJ** [comment]
Hello Mike, I thought you will assign me to this before closing. :)
