### ISSUE TITLE
Develop the Landing Page

### ISSUE THREAD

**Issue by mikehammond** [mowblox/decentralized-vendor-payment-system#6]
https://www.figma.com/proto/tZcDNidHVxVaye7pqVyJB4/PAYFLOW?node-id=102-1731&node-type=canvas&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=102%3A1731&show-proto-sidebar=1

**Comment by Baah-Danso-Kenneth** [comment]
@mikehammond I would want to pick this issue up

**Comment by mikehammond** [comment]
@Baah-Danso-Kenneth Please take it  away
