### ISSUE TITLE
Develop the Dashboard and Related Pages

### ISSUE THREAD

**Issue by mikehammond** [mowblox/decentralized-vendor-payment-system#8]
- Main Dashboard => https://www.figma.com/proto/tZcDNidHVxVaye7pqVyJB4/PAYFLOW?node-id=151-2033&node-type=canvas&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=102%3A1731&show-proto-sidebar=1
- Create a New Payment Link => https://www.figma.com/proto/tZcDNidHVxVaye7pqVyJB4/PAYFLOW?node-id=208-1947&node-type=canvas&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=102%3A1731&show-proto-sidebar=1
- Generate & Copy Payment Link => https://www.figma.com/proto/tZcDNidHVxVaye7pqVyJB4/PAYFLOW?node-id=208-1947&node-type=canvas&scaling=scale-down-width&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=102%3A1731&show-proto-sidebar=1

**Comment by Baah-Danso-Kenneth** [comment]
@mikehammond Please i would like to pick this issue up.

**Comment by mikehammond** [comment]
@Baah-Danso-Kenneth You got it.
